### PR TITLE
Fix crash for `script`, `style`, and `link` tags with no-value type attribute

### LINKED ISSUE #132: bug: Exception thrown for `script`, `style`, and `link` tags no-value `type` attribute
For the config:
```js
{
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true
}
```

The library throws an exception for the following inputs:
1. `<script type />`
   `TypeError: Cannot read properties of undefined (reading 'split')`
1. `<style type />`
   `TypeError: Cannot read properties of undefined (reading 'toLowerCase')`
1. `<link type />`
   `TypeError: Cannot read properties of undefined (reading 'toLowerCase')`

All three errors seem to originate from this if statement:
https://github.com/terser/html-minifier-terser/blob/14b44c7bde1037ece4eae3e12a02493db71d660a/src/htmlminifier.js#L552-L559

Both ` isScriptTypeAttribute()` and `isStyleLinkTypeAttribute()` don't seem to handle the case where `attrValue` is undefined.

### PR DESCRIPTION
**Pull request by KartikSoneji**
Closes #132

### CODE REVIEW

**Review by sibiraj-s — APPROVED** [review]
Looks good 👍

**Comment by sibiraj-s** [comment]
Thanks @KartikSoneji. I totally forgot about this. I will merge this tomorrow.

cc @DanielRuf

**Comment by KartikSoneji** [comment]
No worries, thanks for taking a look.
Let me know if I should rebase this onto master.

**Comment by sibiraj-s** [comment]
Not required, since there are no conflicts. I can squash.

**Comment by sibiraj-s** [comment]
Published in v7.1.0

**Pull request merged**
