### PR TITLE
update clean-css 5.2.0 to ^5.2.0

### PR DESCRIPTION
**Pull request by Tobias-Beck**
clean-css 5.2.0 has security issues. https://www.huntr.dev/bounties/6937a4ed-e41f-4fff-8f9b-8bcbed0f616e/ The issue is fixed in 5.2.2, please update to ^5.2.0 or 5.2.2.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Hi @Tobias-Beck,

thanks for reporting this.

@sibiraj-s will handle and schedule a new release then.

**Comment by sibiraj-s** [comment]
Thanks for reporting this @Tobias-Beck . Unfortunately this will break things as v5.3 and above in clean-css has breaking changes, hence pinned.

I would recommend rather than adding a caret(^), update the dependency by pinning it to v5.2.2 and also commit the lock file. I will be able make a minor patch release then.

**Review by sibiraj-s — CHANGES_REQUESTED** [review]
See https://github.com/terser/html-minifier-terser/pull/140#issuecomment-1341220310

**Comment by DanielRuf** [comment]
Replaced by https://github.com/terser/html-minifier-terser/pull/148

**Pull request closed without merging**
