### PR TITLE
Update clean-css version

### LINKED ISSUE #64: Minifying issue with CSS
Unfortunately, `html-minifier-terser` during minifying with the `minifyCSS: true,` we faced this issue. my code is like this:

```css
div * {
  color: red;
}
```
Bu my code is changed to this:

```css
div*{color:red}
```

And browser cannot understand this selector `div*` it should be `div *`, even in the production level after minifying, is there any property for preventing that issue or is it a bug?

### PR DESCRIPTION
**Pull request by amerllica**
This PR will resolve #64

### CODE REVIEW

**Review by DanielRuf — CHANGES_REQUESTED** [review]
Please revert the changes for dist and lockfile, these will be updated when a new release is done. Thank you.

**Comment by amerllica** [comment]
@DanielRuf, Thanks for your review, I reverted all files except the `package.json` file.

**Comment by DanielRuf** [comment]
It seems some tests are failing. I will check these and will push the changed tests to this PR when I find some time.

**Comment by amerllica** [comment]
@DanielRuf, I checked, by the new version `5.1.3` some tests will be failed, but test work with the version `4.2.3`. weird, I should check it. no worries.

**Comment by DanielRuf** [comment]
That's mostly because clean-css adds quotation marks for URLs by default (and maybe a few more changes).

If you want you can use and adapt the changes from https://github.com/kangax/html-minifier/pull/1098

**Comment by amerllica** [comment]
@DanielRuf, I learned from the given link but I fixed ours with my logic. please check it. thanks.

**Comment by amerllica** [comment]
@DanielRuf, this PR passed All checks.

**Review by DanielRuf — APPROVED** [review]

**Pull request merged**
