### PR TITLE
Add flag to remove newline before tag close

### LINKED ISSUE #84: using `maxLineLength` can introduce newlines that might create bugs in links underline
when using `maxLineLength` the newline added after an `a` tag, if added right before the closing tag, will generate a link where the underline is longer than the text itself.

e.g.
```
const express = require('express')
const { minify } = require('html-minifier-terser') 
const app = express()

const html = `
  Ehi! This is an example for github! <a href="https://website.com">https://website.com/home</a> ain't this nice?
`


app.get('/', (req, res) => {
  res.send(html)
})


app.get('/mini', (req, res) => {
  minify(html, {
      maxLineLength: 10,
    }).then(m => {
      res.send(m)
    })
})


app.listen(5000)
```

`http://localhost:5000`

image

`http://localhost:5000/mini`

image

EDIT:

The same thing happens when the element has similar `text-decoration`s like `underline`. I propose to avoid adding newlines before any closing tag.

### PR DESCRIPTION
**Pull request by lucamattiazzi**
creates a new flag that allows the user to avoid adding newlines before the closing tag in order to both solve issue #84 and not change how the library works

Fixes #84

### CODE REVIEW

**Comment by sibiraj-s** [comment]
I have some mixed opinions about this option. Let me get back on this.

**Comment by sibiraj-s** [comment]
I think this is fine. This is the shortest and non breaking fix can be done I guess. 

Just a thought, maxLineLength is a nice to have option, but I am not sure a minifier must have it. It makes sense for a formatter like prettier.

I am also having thoughts about switching to some well maintained parser. like `parse5` or `htmlparser2` or some other parsers, so that this package can let alone focus on minifying html.

**Comment by DanielRuf** [comment]
>     * I am also having thoughts about switching to some well maintained parser. like `parse5` or `htmlparser2` or some other parsers, so that this package can let alone focus on minifying html.

Definitely a good idea. I am currently unsure but afaik there were discussions regarding this for html-minifier.
See https://github.com/kangax/html-minifier/issues/155

**Comment by sibiraj-s** [comment]
> Definitely a good idea. I am currently unsure but afaik there were discussions regarding this for html-minifier.
See kangax/html-minifier#155

Thanks, will check it out.

**Comment by sibiraj-s** [comment]
I would prefer this

```js
const endTagMatch = results[0].match(endTag)
const forceSameLine = endTagMatch && inlineTextTags(endTagMatch[1])
```

Its breaking, but it is the correct behaviour I think. May be for v7.

**Review by sibiraj-s — APPROVED** [review]

**Review by DanielRuf — APPROVED** [review]

**Comment by DanielRuf** [comment]
> **CI - Node 16 (ubuntu-latest) ** Expected — Waiting for status to be reported

I'm wondering what happened with the CI build.

**Comment by sibiraj-s** [comment]
> > **CI - Node 16 (ubuntu-latest)** Expected — Waiting for status to be reported
> 
> I'm wondering what happened with the CI build.

Yeah I was waiting for the same. I think it is the branch protection rule. checking

**Comment by sibiraj-s** [comment]
Okay. Found it I guess. the workflow was waiting for approval to run for first time contributors. Since it is not approved for more than 30 days, I got expired.

**Comment by DanielRuf** [comment]
> Okay. Found it I guess. the workflow was waiting for approval to run for first time contributors. Since it is not approved for more than 30 days, It got expired.

Ah, can we somehow trigeger a new build? Optionally we can maybe push a commit `Trigger CI` without any changes (`--allow-empty`).

**Comment by sibiraj-s** [comment]
> Ah, can we somehow trigeger a new build? Optionally we can maybe push a commit `Trigger CI` without any changes (`--allow-empty`).

Pushed a small change. we can squash merge the PR.

**Comment by sibiraj-s** [comment]
Making a release now.

**Comment by sibiraj-s** [comment]
Published in [v6.1.0](https://github.com/terser/html-minifier-terser/releases/tag/v6.1.0)

**Comment by DanielRuf** [comment]
@lucamattiazzi thank you very much for your contribution :+1:

**Comment by lucamattiazzi** [comment]
thank you for your library! and thanks for approving&merging!

**Pull request merged**
