### PR TITLE
Build Demo

### PR DESCRIPTION
**Pull request by sibiraj-s**
- fixed workflows from running on multiple same versions, just run on known node versions supported
- removes `dist/` directory from source. the only reason I see for that forlder to exist here is for the docs
- demo is now built and published using github actions

### CODE REVIEW

**Comment by sibiraj-s** [comment]
@DanielRuf I am thinking of using github actions to publish to npm.

**Comment by DanielRuf** [comment]
> @DanielRuf I am thinking of using github actions to publish to npm.

Sounds good, so this can be automated then.

**Comment by sibiraj-s** [comment]
> > @DanielRuf I am thinking of using github actions to publish to npm.
> 
> Sounds good, so this can be automated then.

Awesome. I will start then I have added an environment, once the action is setup, Any one of the maintainer will need to approve the release.

**Comment by sibiraj-s** [comment]
Let's merge this?

**Review by DanielRuf — APPROVED** [review]

**Comment by DanielRuf** [comment]
> Let's merge this?

Feel free to merge when the conflicts are resolved.

**Pull request merged**
