### PR TITLE
Add the type definitions file - closes #20

### LINKED ISSUE #20: typings
maybe we could merge https://www.npmjs.com/package/@types/html-minifier into this package?

### PR DESCRIPTION
**Pull request by DanielRuf**
This adds the type definitions file so that TypeScript projects can consume and use them.

### CODE REVIEW

**Comment by jantimon** [comment]
Looks good to me 👍

@types/html-minifier has 3 dependencies:
https://www.npmjs.com/package/@types/html-minifier

- @types/clean-css
- @types/relateurl
- @types/uglify-js

Will adding them as devDependencies be enough to work properly?

**Comment by DanielRuf** [comment]
I think so. They are added in the package.json file in this PR.
`@types/uglify-js` is not needed anymore as `terser` is used now and for that there is only a stub, see https://unpkg.com/browse/@types/terser@3.12.0/package.json

**Comment by DanielRuf** [comment]
I think so. They are added in the package.json file in this PR.
`@types/uglify-js` is not needed anymore as `terser` is used now and for that there is only a stub, see https://unpkg.com/browse/@types/terser@3.12.0/package.json and https://unpkg.com/browse/@types/terser@3.12.0/README.md

**Comment by DanielRuf** [comment]
I have read the same thread yesterday.

Normally I would say `devDependencies` because types and TypeScript are not directly used in production and only useful for development.`

**Comment by jantimon** [comment]
If dependents of `html-minifier-terser` will use it, it is a public dependency not a dev dependency.

If you don't want to add it to dependencies that is also fine but in that case we should not merge this pullrequest - as dependent builds will fail otherwise.

Maybe we can create @types/html-minifier-terser instead?

**Comment by DanielRuf** [comment]
> Maybe we can create @types/html-minifier-terser instead?

Makes more sense. But I have amended the commit and moved them to `dependencies` so there should not be any issues now.

**Comment by jantimon** [comment]
Both ways will work fine for IDE support and build type checks.

**Comment by jantimon** [comment]
So pick the one you prefer :)

**Comment by DanielRuf** [comment]
I guess I can close this PR as trhere is now https://www.npmjs.com/package/@types/html-minifier-terser

**Comment by DanielRuf** [comment]
Closing as this may be obsolete now.

**Pull request closed without merging**
