### PR TITLE
Migrating from browserify to rollup

### PR DESCRIPTION
**Pull request by sibiraj-s**
Migrates from browserify to rollup.

- this allows creating multiple builds like esm/umd/cjs builds easier. this will allow us to switch to es modules in future and also provide backward compatible scripts

New Files created.
- `dist/htmlminifier.umd.bundle.js` (for browsers)
- `dist/htmlminifier.umd.bundle.min.js` (for browsers minified)
- `dist/htmlminifier.esm.bundle.js` (for scripts using modules in browsers)
- `dist/htmlminifier.js` (for nodejs using import script)

Also supports new [exports syntax](https://nodejs.org/api/packages.html#packages_exports_sugar). we should be able to provide conditional export of file and also later switch to module without breaking changes.

**Breaking change**:
- the `dist/htmlminifier.js` is now ESM, the browser version can be found in `umd/esm.bundle.js`.
- browser bundles no longer adds `require` to the window scope.

Note: the dist files are not published to npm. hence its very hightly unlike to affect end users.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Hi @sibiraj-s,

can you please adjust the PR title and description so it gets easier to understand that this is about "change the build setup to rollup for faster / easier builds"?

That would be great =)

**Comment by sibiraj-s** [comment]
Can I go ahead and merge this?

**Comment by DanielRuf** [comment]
> Can I go ahead and merge this?

I took a quick look and the changes look good to me. Sure, you can go ahead.

**Comment by sibiraj-s** [comment]
Thanks. @DanielRuf

**Pull request merged**
